import type { AgentSystemRisk } from '../../api/types.ts';

export interface GoogleCommandContract {
  flags: Record<string, 'boolean' | 'value' | 'read' | 'write'>;
  arguments: string[];
  risk: AgentSystemRisk;
}

// reviewed against gogcli v0.42.0, commit 792107a3a77dde04bd41bd176abfd15ff4aa24d6.
// admit canonical commands and only their inspected flags; aliases remain unavailable.
export const googleCommandContract: Record<string, GoogleCommandContract> = {
  'gmail search': {
    flags: {
      '--from-contact': 'value',
      '--max': 'value',
      '--limit': 'value',
      '--page': 'value',
      '--cursor': 'value',
      '--all': 'boolean',
      '--all-pages': 'boolean',
      '--allpages': 'boolean',
      '--fail-empty': 'boolean',
      '--non-empty': 'boolean',
      '--require-results': 'boolean',
      '--count': 'boolean',
      '--oldest': 'boolean',
      '--timezone': 'value',
      '-z': 'value',
      '--local': 'boolean',
    },
    arguments: ['value'],
    risk: 'read',
  },
  'gmail get': {
    flags: {
      '--use-indexed-attachment-ids': 'boolean',
      '--format': 'value',
      '--headers': 'value',
      '--sanitize-content': 'boolean',
      '--sanitize': 'boolean',
      '--safe': 'boolean',
    },
    arguments: ['value'],
    risk: 'read',
  },
  'gmail send': {
    flags: {
      '--to': 'value',
      '--cc': 'value',
      '--bcc': 'value',
      '--subject': 'value',
      '--body': 'value',
      '--body-file': 'read',
      '--body-html': 'value',
      '--body-html-file': 'read',
      '--raw-file': 'read',
      '--reply-to-message-id': 'value',
      '--in-reply-to': 'value',
      '--thread-id': 'value',
      '--reply-all': 'boolean',
      '--reply-to': 'value',
      '--attach': 'read',
      '--from': 'value',
      '--signature-from': 'value',
      '--signature-file': 'read',
      '--quote': 'boolean',
    },
    arguments: [],
    risk: 'write',
  },
  'gmail attachment': {
    flags: {
      '--use-indexed-attachment-ids': 'boolean',
      '--out': 'write',
      '--output': 'write',
      '--name': 'value',
      '--inline': 'boolean',
      '--inline-max-bytes': 'value',
    },
    arguments: ['value', 'value'],
    risk: 'read',
  },
  'calendar events': {
    flags: {
      '--cal': 'value',
      '--calendars': 'value',
      '--from': 'value',
      '--to': 'value',
      '--today': 'boolean',
      '--tomorrow': 'boolean',
      '--week': 'boolean',
      '--days': 'value',
      '--week-start': 'value',
      '--max': 'value',
      '--limit': 'value',
      '--page': 'value',
      '--cursor': 'value',
      '--all-pages': 'boolean',
      '--allpages': 'boolean',
      '--fail-empty': 'boolean',
      '--non-empty': 'boolean',
      '--require-results': 'boolean',
      '--query': 'value',
      '--event-types': 'value',
      '--all': 'boolean',
      '--private-prop-filter': 'value',
      '--shared-prop-filter': 'value',
      '--fields': 'value',
      '--weekday': 'boolean',
      '--location': 'boolean',
      '--sort': 'value',
      '--order': 'value',
      '--timezone': 'value',
      '--tz': 'value',
    },
    arguments: ['value'],
    risk: 'read',
  },
  'calendar event': {
    flags: {
      '--timezone': 'value',
      '--tz': 'value',
    },
    arguments: ['value', 'value'],
    risk: 'read',
  },
  'calendar calendars': {
    flags: {
      '--max': 'value',
      '--limit': 'value',
      '--page': 'value',
      '--cursor': 'value',
      '--all': 'boolean',
      '--all-pages': 'boolean',
      '--allpages': 'boolean',
      '--fail-empty': 'boolean',
      '--non-empty': 'boolean',
      '--require-results': 'boolean',
    },
    arguments: [],
    risk: 'read',
  },
  'calendar create': {
    flags: {
      '--summary': 'value',
      '--from': 'value',
      '--to': 'value',
      '--start-timezone': 'value',
      '--from-timezone': 'value',
      '--end-timezone': 'value',
      '--to-timezone': 'value',
      '--timezone': 'value',
      '--tz': 'value',
      '--description': 'value',
      '--location': 'value',
      '--attendees': 'value',
      '--all-day': 'boolean',
      '--rrule': 'value',
      '--reminder': 'value',
      '--no-reminders': 'boolean',
      '--event-color': 'value',
      '--visibility': 'value',
      '--transparency': 'value',
      '--send-updates': 'value',
      '--guests-can-invite': 'boolean',
      '--guests-can-modify': 'boolean',
      '--guests-can-see-others': 'boolean',
      '--with-meet': 'boolean',
      '--source-url': 'value',
      '--source-title': 'value',
      '--attachment': 'value',
      '--private-prop': 'value',
      '--shared-prop': 'value',
      '--event-type': 'value',
      '--focus-auto-decline': 'value',
      '--focus-decline-message': 'value',
      '--focus-chat-status': 'value',
      '--ooo-auto-decline': 'value',
      '--ooo-decline-message': 'value',
      '--working-location-type': 'value',
      '--working-office-label': 'value',
      '--working-building-id': 'value',
      '--working-floor-id': 'value',
      '--working-desk-id': 'value',
      '--working-custom-label': 'value',
    },
    arguments: ['value'],
    risk: 'write',
  },
  'calendar update': {
    flags: {
      '--summary': 'value',
      '--from': 'value',
      '--to': 'value',
      '--start-timezone': 'value',
      '--from-timezone': 'value',
      '--end-timezone': 'value',
      '--to-timezone': 'value',
      '--description': 'value',
      '--location': 'value',
      '--attendees': 'value',
      '--add-attendee': 'value',
      '--attachment': 'value',
      '--all-day': 'boolean',
      '--rrule': 'value',
      '--reminder': 'value',
      '--no-reminders': 'boolean',
      '--event-color': 'value',
      '--visibility': 'value',
      '--transparency': 'value',
      '--guests-can-invite': 'boolean',
      '--guests-can-modify': 'boolean',
      '--guests-can-see-others': 'boolean',
      '--with-meet': 'boolean',
      '--regenerate-meet': 'boolean',
      '--regenerate-zoom': 'boolean',
      '--remove-zoom': 'boolean',
      '--scope': 'value',
      '--original-start': 'value',
      '--private-prop': 'value',
      '--shared-prop': 'value',
      '--event-type': 'value',
      '--focus-auto-decline': 'value',
      '--focus-decline-message': 'value',
      '--focus-chat-status': 'value',
      '--ooo-auto-decline': 'value',
      '--ooo-decline-message': 'value',
      '--working-location-type': 'value',
      '--working-office-label': 'value',
      '--working-building-id': 'value',
      '--working-floor-id': 'value',
      '--working-desk-id': 'value',
      '--working-custom-label': 'value',
      '--send-updates': 'value',
    },
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'calendar delete': {
    flags: {
      '--scope': 'value',
      '--original-start': 'value',
      '--send-updates': 'value',
    },
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'drive ls': {
    flags: {
      '--max': 'value',
      '--limit': 'value',
      '--page': 'value',
      '--cursor': 'value',
      '--query': 'value',
      '--parent': 'value',
      '--all': 'boolean',
      '--global': 'boolean',
      '--all-drives': 'boolean',
      '--fields': 'value',
      '--sort': 'value',
      '--order': 'value',
    },
    arguments: [],
    risk: 'read',
  },
  'drive search': {
    flags: {
      '--raw-query': 'boolean',
      '--raw': 'boolean',
      '--max': 'value',
      '--limit': 'value',
      '--page': 'value',
      '--cursor': 'value',
      '--all-drives': 'boolean',
      '--drive': 'value',
      '--drive-id': 'value',
      '--parent': 'value',
    },
    arguments: ['value'],
    risk: 'read',
  },
  'drive get': {
    flags: {
      '--fields': 'value',
    },
    arguments: ['value'],
    risk: 'read',
  },
  'drive upload': {
    flags: {
      '--name': 'value',
      '--parent': 'value',
      '--replace': 'value',
      '--if-version': 'value',
      '--mime-type': 'value',
      '--keep-revision-forever': 'boolean',
      '--keep-frontmatter': 'boolean',
    },
    arguments: ['read'],
    risk: 'write',
  },
  'drive download': {
    flags: {
      '--out': 'write',
      '--output': 'write',
      '--format': 'value',
      '--tab': 'value',
      '--overwrite': 'boolean',
    },
    arguments: ['value'],
    risk: 'read',
  },
  'drive mkdir': {
    flags: {
      '--parent': 'value',
    },
    arguments: ['value'],
    risk: 'write',
  },
  'drive copy': {
    flags: {
      '--parent': 'value',
    },
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'drive delete': {
    flags: {
      '--permanent': 'boolean',
    },
    arguments: ['value'],
    risk: 'write',
  },
  'drive rename': {
    flags: {},
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'drive move': {
    flags: {
      '--parent': 'value',
    },
    arguments: ['value'],
    risk: 'write',
  },
  'drive share': {
    flags: {
      '--to': 'value',
      '--email': 'value',
      '--domain': 'value',
      '--role': 'value',
      '--discoverable': 'boolean',
      '--notify': 'boolean',
    },
    arguments: ['value'],
    risk: 'write',
  },
  'drive unshare': {
    flags: {},
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'docs insert': {
    flags: {
      '--index': 'value',
      '--at': 'value',
      '--occurrence': 'value',
      '--match-case': 'boolean',
      '--file': 'read',
      '-f': 'read',
      '--tab': 'value',
      '--segment': 'value',
    },
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'docs write': {
    flags: {
      '--text': 'value',
      '--file': 'read',
      '--replace': 'boolean',
      '--append': 'boolean',
      '--check-orphans': 'boolean',
      '--pageless': 'boolean',
      '--page-size': 'value',
      '--page-width': 'value',
      '--page-height': 'value',
      '--margin-left': 'value',
      '--margin-right': 'value',
      '--margin-top': 'value',
      '--margin-bottom': 'value',
      '--tab': 'value',
      '--font-family': 'value',
      '--font-size': 'value',
      '--text-color': 'value',
      '--bg-color': 'value',
      '--code': 'boolean',
      '--bold': 'boolean',
      '--no-bold': 'boolean',
      '--italic': 'boolean',
      '--no-italic': 'boolean',
      '--underline': 'boolean',
      '--no-underline': 'boolean',
      '--strikethrough': 'boolean',
      '--strike': 'boolean',
      '--no-strikethrough': 'boolean',
      '--no-strike': 'boolean',
      '--alignment': 'value',
      '--line-spacing': 'value',
      '--spacing-mode': 'value',
      '--heading-level': 'value',
      '--named-style': 'value',
      '--bullets': 'boolean',
      '--ordered': 'boolean',
      '--bullet-preset': 'value',
      '--no-bullets': 'boolean',
      '--indent-start': 'value',
      '--indent-first-line': 'value',
      '--indent-end': 'value',
      '--space-above': 'value',
      '--space-below': 'value',
      '--keep-with-next': 'boolean',
      '--keep-lines-together': 'boolean',
    },
    arguments: ['value'],
    risk: 'write',
  },
  'docs info': {
    flags: {},
    arguments: ['value'],
    risk: 'read',
  },
  'docs cat': {
    flags: {
      '--max-bytes': 'value',
      '--tab': 'value',
      '--all-tabs': 'boolean',
      '--raw': 'boolean',
      '--numbered': 'boolean',
      '-N': 'boolean',
      '--chips': 'boolean',
    },
    arguments: ['value'],
    risk: 'read',
  },
  'docs create': {
    flags: {
      '--parent': 'value',
      '--pageless': 'boolean',
    },
    arguments: ['value'],
    risk: 'write',
  },
  'docs export': {
    flags: {
      '--out': 'write',
      '--output': 'write',
      '--format': 'value',
      '--tab': 'value',
      '--overwrite': 'boolean',
    },
    arguments: ['value'],
    risk: 'read',
  },
  'docs copy': {
    flags: {
      '--parent': 'value',
    },
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'sheets get': {
    flags: {
      '--dimension': 'value',
      '--render': 'value',
    },
    arguments: ['value', 'value'],
    risk: 'read',
  },
  'sheets update': {
    flags: {
      '--input': 'value',
      '--values-json': 'value',
      '--copy-validation-from': 'value',
      '--fail-on-formula-error': 'boolean',
    },
    arguments: ['value', 'value', 'value'],
    risk: 'write',
  },
  'sheets append': {
    flags: {
      '--input': 'value',
      '--insert': 'value',
      '--values-json': 'value',
      '--copy-validation-from': 'value',
    },
    arguments: ['value', 'value', 'value'],
    risk: 'write',
  },
  'sheets clear': {
    flags: {},
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'sheets create': {
    flags: {
      '--sheets': 'value',
      '--parent': 'value',
    },
    arguments: ['value'],
    risk: 'write',
  },
  'sheets metadata': {
    flags: {},
    arguments: ['value'],
    risk: 'read',
  },
  'sheets export': {
    flags: {
      '--out': 'write',
      '--output': 'write',
      '--format': 'value',
      '--overwrite': 'boolean',
    },
    arguments: ['value'],
    risk: 'read',
  },
  'sheets copy': {
    flags: {
      '--parent': 'value',
    },
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'slides info': {
    flags: {},
    arguments: ['value'],
    risk: 'read',
  },
  'slides create': {
    flags: {
      '--parent': 'value',
      '--template': 'value',
    },
    arguments: ['value'],
    risk: 'write',
  },
  'slides export': {
    flags: {
      '--out': 'write',
      '--output': 'write',
      '--format': 'value',
      '--overwrite': 'boolean',
    },
    arguments: ['value'],
    risk: 'read',
  },
  'slides copy': {
    flags: {
      '--parent': 'value',
    },
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'slides list-slides': {
    flags: {},
    arguments: ['value'],
    risk: 'read',
  },
  'slides update-notes': {
    flags: {
      '--notes': 'value',
      '--notes-file': 'read',
    },
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'slides insert-text': {
    flags: {
      '--insertion-index': 'value',
      '--replace': 'boolean',
      '--row': 'value',
      '--col': 'value',
    },
    arguments: ['value', 'value', 'value'],
    risk: 'write',
  },
  'contacts list': {
    flags: {
      '--max': 'value',
      '--limit': 'value',
      '--page': 'value',
    },
    arguments: [],
    risk: 'read',
  },
  'contacts search': {
    flags: {
      '--max': 'value',
      '--limit': 'value',
    },
    arguments: ['value'],
    risk: 'read',
  },
  'contacts get': {
    flags: {},
    arguments: ['value'],
    risk: 'read',
  },
  'contacts create': {
    flags: {
      '--given': 'value',
      '--family': 'value',
      '--email': 'value',
      '--phone': 'value',
      '--org': 'value',
      '--title': 'value',
      '--url': 'value',
      '--note': 'value',
      '--address': 'value',
      '--gender': 'value',
      '--custom': 'value',
      '--relation': 'value',
    },
    arguments: [],
    risk: 'write',
  },
  'contacts update': {
    flags: {
      '--given': 'value',
      '--family': 'value',
      '--email': 'value',
      '--phone': 'value',
      '--org': 'value',
      '--title': 'value',
      '--url': 'value',
      '--note': 'value',
      '--address': 'value',
      '--gender': 'value',
      '--custom': 'value',
      '--relation': 'value',
      '--from-file': 'read',
      '--ignore-etag': 'boolean',
      '--birthday': 'value',
      '--notes': 'value',
    },
    arguments: ['value'],
    risk: 'write',
  },
  'contacts delete': {
    flags: {},
    arguments: ['value'],
    risk: 'write',
  },
  'tasks lists list': {
    flags: {
      '--max': 'value',
      '--limit': 'value',
      '--page': 'value',
      '--cursor': 'value',
      '--all': 'boolean',
      '--all-pages': 'boolean',
      '--allpages': 'boolean',
      '--fail-empty': 'boolean',
      '--non-empty': 'boolean',
      '--require-results': 'boolean',
    },
    arguments: [],
    risk: 'read',
  },
  'tasks lists create': {
    flags: {},
    arguments: ['value'],
    risk: 'write',
  },
  'tasks list': {
    flags: {
      '--max': 'value',
      '--limit': 'value',
      '--page': 'value',
      '--cursor': 'value',
      '--all': 'boolean',
      '--all-pages': 'boolean',
      '--allpages': 'boolean',
      '--fail-empty': 'boolean',
      '--non-empty': 'boolean',
      '--require-results': 'boolean',
      '--show-completed': 'boolean',
      '--show-deleted': 'boolean',
      '--show-hidden': 'boolean',
      '--show-assigned': 'boolean',
      '--due-min': 'value',
      '--due-max': 'value',
      '--completed-min': 'value',
      '--completed-max': 'value',
      '--updated-min': 'value',
    },
    arguments: ['value'],
    risk: 'read',
  },
  'tasks get': {
    flags: {},
    arguments: ['value', 'value'],
    risk: 'read',
  },
  'tasks add': {
    flags: {
      '--title': 'value',
      '--notes': 'value',
      '--due': 'value',
      '--parent': 'value',
      '--previous': 'value',
      '--repeat': 'value',
      '--recur': 'value',
      '--recur-rrule': 'value',
      '--repeat-count': 'value',
      '--repeat-until': 'value',
    },
    arguments: ['value'],
    risk: 'write',
  },
  'tasks update': {
    flags: {
      '--title': 'value',
      '--notes': 'value',
      '--due': 'value',
      '--status': 'value',
    },
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'tasks done': {
    flags: {},
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'tasks undo': {
    flags: {},
    arguments: ['value', 'value'],
    risk: 'write',
  },
  'tasks delete': {
    flags: {},
    arguments: ['value', 'value'],
    risk: 'write',
  },
};
