import type { AgentPathProjection } from './resolve-agent-paths.ts';

export const managedCodexPathMarker = '# agent-system: managed-path-v1';
export const manualCodexPathMarker = '# agent-system: manual-path-v1';

export type CodexPathConfigOwnership = 'managed' | 'manual' | 'user';

export function classifyCodexPathConfig(source: string): CodexPathConfigOwnership {
  if (source.split(/\r?\n/u).includes(managedCodexPathMarker)) return 'managed';
  if (source.split(/\r?\n/u).includes(manualCodexPathMarker)) return 'manual';
  return 'user';
}

export function renderCodexPathConfig(path: string): string {
  return `${managedCodexPathMarker}
# generated by openclaw agent-system install; manual edits will be replaced

allow_login_shell = false

[features]
shell_snapshot = true

[shell_environment_policy.set]
PATH = ${JSON.stringify(path)}
`;
}

export function inspectCodexPathConfig(
  source: string,
  projection: AgentPathProjection,
): {
  loginShellDisabled: boolean;
  ownership: CodexPathConfigOwnership;
  pathMatches: boolean;
} {
  const ownership = classifyCodexPathConfig(source);
  const firstTableIndex = source.search(/^\s*\[/mu);
  const rootSource = firstTableIndex < 0 ? source : source.slice(0, firstTableIndex);
  const loginShellDisabled = /^\s*allow_login_shell\s*=\s*false\s*(?:#.*)?$/mu.test(rootSource);
  const match = /^PATH = ("(?:[^"\\]|\\.)*")$/mu.exec(source);
  if (!match?.[1]) return { loginShellDisabled, ownership, pathMatches: false };
  try {
    const path = JSON.parse(match[1]) as unknown;
    if (typeof path !== 'string') return { loginShellDisabled, ownership, pathMatches: false };
    return {
      loginShellDisabled,
      ownership,
      pathMatches: path === projection.path,
    };
  } catch {
    return { loginShellDisabled, ownership, pathMatches: false };
  }
}
